version: '3.4'

volumes:
  mysql-volume:

services:
    database:
        image: mysql:8.0.22
        ports:
         - "3306:3306"

        volumes:
        - mysql-volume:/var/lib/mysql
        environment: 
            MYSQL_USER: root
            MYSQL_PASSWORD: 12345
            MYSQL_DATABASE: GaHipHop

    gahiphop_api:
        image: ${DOCKER_REGISTRY-}gahiphopapi
        build:
            context: .
            dockerfile: GaHipHop_API/Dockerfile
